Password for social login
balena-io/docs pull request #1661
Opened 2021-03-19 11:45 UTC by danthegoodman1

See #242

2021-03-19 13:24 UTC, vipulgupta2048 reviewed
@danthegoodman1 Need a better commit message, we all love good messages for our history

2021-03-19 14:41 UTC, pdcastro approved these changes

2021-03-19 14:43 UTC, xginn8 commented on pages/learn/manage/account.md
> +To add a password to an account created with a social login (Google, Github), navigate to the *Preferences* page found by clicking on your profile in the top right of the dashboard. Under the *Accoun
we should link to preferences here, just like in the following note

2021-03-19 14:43 UTC, pdcastro requested changes
Oh, I had missed Vipul's comment re commit message. There's a commit that reads literally:
 `Added 'a'`

2021-03-19 16:07 UTC, danthegoodman1 commented
> Oh, I had missed Vipul's comment re commit message. There's a commit that reads literally:
> `Added 'a'`

Yeah I did that because the first one I forgot to add a `Change-type`

2021-03-19 16:28 UTC, pdcastro commented
> > Oh, I had missed Vipul's comment re commit message. There's a commit that reads literally:
> > `Added 'a'`
> 
> Yeah I did that because the first one I forgot to add a `Change-type`

The point is that `Added 'a'` means little when the sentence in read in the [CHANGELOG](https://github.com/balena-io/docs/blob/master/CHANGELOG.md), or with `git log`.

2021-03-19 16:28 UTC, pdcastro approved these changes

2021-03-19 16:30 UTC, vipulgupta2048 commented
@balena-ci rebase

2021-03-19 17:21 UTC, danthegoodman1 commented
@balena-ci rebase

2021-03-19 17:23 UTC, pdcastro requested changes
There is a merge commit in the list of commits. Please drop the merge commit, and use rebase instead of merge (we use rebase across all balena repos).

2021-03-19 17:30 UTC, danthegoodman1 commented
@balena-ci rebase

2021-03-20 01:07 UTC, pdcastro approved these changes

2021-03-20 01:07 UTC, pdcastro commented
@balena-ci rebase

2021-03-20 01:15 UTC, merged

2021-03-23 13:07 UTC, vipulgupta2048 commented
Resolves #242