Fix most of the vulnerabilities
balena-io/docs pull request #1790
Opened 2021-03-30 14:42 UTC by mbalamat

* Update dependencies
	> Used the npm-check-updates tool
	After this npm finds
	10 vulnerabilities (6 low, 4 high)

* Remove and replace deprecated module with alternative
	> More info:
	https://www.npmjs.com/package/extract-text-webpack-plugin

* Remove unused package metalsmith-prefixoid
	After this npm finds
	9 vulnerabilities (6 low, 3 high)

All the vulnerabilities left come from @balena/doxx

Connects-to: https://github.com/balena-io/docs/issues/1665
Change-type: patch
Signed-off-by: Marios Balamatsias <mbalamatsias@gmail.com>

2021-03-30 15:26 UTC, vipulgupta2048 requested changes
![Screenshot from 2021-03-30 20-55-14](https://user-images.githubusercontent.com/22801822/113014517-485d5780-919a-11eb-9561-111f13fe6f58.png)
Can't see the welcome tab in the sidebar with the top header going way out of proportions.

2021-04-19 18:17 UTC, karaxuna commented
@vipulgupta2048 broken navbar was caused by upgrading bootstrap to next major version. Reverted this change. Also fixed highlight.js errors caused by moving to next major version.

2021-04-20 12:05 UTC, karaxuna commented
@balena-ci rebase

2021-04-20 12:51 UTC, vipulgupta2048 approved these changes

2021-04-20 12:51 UTC, merged