develop/hardware: Update I2C example in the i2c-and-spi section
balena-io/docs pull request #2723
Opened 2023-05-31 09:59 UTC by acostach

The existing sample application is now old, let's use the balena-sense project as an example for I2C.

Change-type: patch

---

> *Please make sure to read the [CONTRIBUTING](https://github.com/balena-io/docs/blob/master/CONTRIBUTING.md) document before opening the PR for relevant information on contributing to the documentation. Thanks!*

2023-05-31 11:02 UTC, lurch commented on pages/learn/develop/hardware/i2c-and-spi.md
> +Single-container fleets run in privileged modeby default. If security and sandboxing are required then a multicontainer release should be created, even if only a single service is required.
"modeby" -> "mode by" ?

2023-05-31 11:24 UTC, acostach commented on pages/learn/develop/hardware/i2c-and-spi.md
> +Single-container fleets run in privileged modeby default. If security and sandboxing are required then a multicontainer release should be created, even if only a single service is required.
Fixed, thanks for spotting that typo

2023-05-31 12:50 UTC, lmbarros requested changes
This looks great to me Alexandru! The CI checks are complaining that `myservice` is an unknown word :roll_eyes: . I added comments with suggestions that will hopefully make this check pass.

2023-06-01 16:33 UTC, lmbarros commented
LGTM

2023-06-01 16:34 UTC, merged